trigger: none


pool:
  name : vinod_pool

stages: 
  - stage: build_stage
    displayName: init_fmt_validate_plan
    jobs:
      - job: init2plan
        displayName: init2plan
        steps: 
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            backendServiceArm: 'vinod_SC'
            backendAzureRmStorageAccountName: 'vinodstg123'
            backendAzureRmContainerName: 'vinodcontainer'
            backendAzureRmKey: 'dev.terraform.tfstate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'custom'
            outputTo: 'console'
            customCommand: 'fmt'
            environmentServiceNameAzureRM: 'vinod_SC'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'

        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            environmentServiceNameAzureRM: 'vinod_SC'

  - stage: Scan_Stage 
    displayName: init_fmt_validate_plan
    jobs:
      - job: scan_of_code
        displayName: tfsec
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'


  - stage: approval_Apply_Stage
    displayName: Approval_Apply
    jobs:
      - job: approval
        pool: server
        displayName: manual_approval
        steps:  
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'vsondhiya@gmail.com'
            approvers: 'vsondhiya@gmail.com'
            onTimeout: 'resume'
      - job: apply
        dependsOn: approval
        displayName: Terraform Apply
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            environmentServiceNameAzureRM: 'vinod_SC'
    
